services:
  - type: web
    name: frontend
    env: static
    staticPublishPath: dist # your build folder name here
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
